- data/metadata.json
- includes/analytics.njk
- includes/faq.njk
- includes/head.njk
- index.njk
This PR:
- Adds basic analytics
- Uses absolute URLs for social sharing cards, 
- Makes a minor copy tweak
> Add analytics, social sharing images fix, and copy tweaks

- .github/CONTRIBUTING.md
- netlify/functions/next.js
- netlify/functions/previous.js
- netlify/functions/random.js
This PR updates the path of the Netlify functions.
> Netlify function fix

- .github/ISSUE_TEMPLATE/addition.yml
- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/code-of-conduct.yml
- .github/ISSUE_TEMPLATE/feature-suggestion.yml
- .github/ISSUE_TEMPLATE/other.yml
> Add issue templates

- includes/nav.njk
- includes/script.njk
- includes/widget.njk
This PR adds `referrerpolicy="no-referrer-when-downgrade"` to (hopefully) handle Chromium browsers handling of URLs. See https://github.com/maxboeck/webring/issues/22.
> Add referrerpolicy

- data/members.json
- includes/footer.njk
- includes/script.njk
- includes/widget.njk
- package.json
This PR adds a placeholder URL for the "Your name here" `members.json` entry, which may be causing the `error decoding lambda response: error decoding lambda response: invalid type "<nil>" for "headers" key "Location"` error.
> Add placeholder URL

- .github/CONTRIBUTING.md
- data/members.json
- includes/members.njk
- site.css
This PR allows a member to flag if they are either hiring or seeking work.
> Add employment metadata

- data/members.json
> Add Andrew Hedges to the 🕸️💍

- data/members.json
> chore: add EJ Mason to the webring

- data/members.json
I want to play with the cool kids!
> Add Eric Eggert/yatil.net

- data/members.json
> Add Mike Herchel to members.json

- data/members.json
Thanks a lot for this initiative 🙌🏼
> Add My Info (Taner Aydın)

- data/members.json
Hi, kindly add me to the a11y web ring club. Currently, my site is hosted in Netlify and I am hoping that will not be an issue. Thank you for starting this.
> Add Winnie to web ring

- .github/CONTRIBUTING.md
- README.md
This PR builds off of https://github.com/ericwbailey/a11y-webring.club/pull/67. It updates the contribution instructions.
> Update contribution instructions

- includes/nav.njk
- includes/script.njk
- includes/widget.njk
This PR addresses https://github.com/ericwbailey/a11y-webring.club/issues/52. It updates the webring member code to use  `referrerpolicy="strict-origin"`.
> Add referrer header

- site.css
This PR addresses https://github.com/ericwbailey/a11y-webring.club/issues/72. It adds better support for Forced Colors Mode.
> Support Forced Colors Mode

- functions/common/utils.js
- netlify.toml
Did a bit more digging, looks like all I was missing was the addition of a `included_files` option for the functions to be able to "see" the full `data/members` folder since it's a dynamic input instead of a static one.
This time, I set up a Netlify account and tested it with a few options first before this one ended up working. So confidence is much higher now! 😅
> Netlify Functions build fix for #60

- Alicia- edit
> Create Alicia- edit - remove rss

- data/members/Luce Carević.json
> Create Luce Carević.json

- data/members/Adam Norris.json
Hey, I would like to be added to the a11y webring. Thank you!
> Add Adam Norris.json

- data/members/Mike Mai.json
Let's hope I didn't mess up this time.
> Add Mike Mai to webring

- data/members/Matthew Hallonbacka.json
The full webring code is on the "About this website" page, the footer contains just the "Next" link - I hope this works!
> Add Matthew Hallonbacka to webring

- data/members/Darek Kay.json
I'd love to join the accessibility webring!
I've added the webring links to my [homepage](https://darekkay.com/).
> Add Darek Kay

- data/members/Seirdy.json
The page includes an accessibility statement but also describes other standards.
> Add accessibility statement for seirdy.one

- data/members/Sara Joy.json
> May I join? Adding sarajoy.dev

- data/members/DJ Chase.json
This PR (hopefully!) addresses [this conversation](https://github.com/ericwbailey/a11y-webring.club/pull/111#issuecomment-1625639282).
> Update DJ Chase.json

- data/members/Kehinde Adeleke.json
Add entry json file to member directory.
> feat: add member entry

- data/members/Devon Persing.json
Adding Mastodon and updating status.
> Update Devon Persing.json

- data/members/Sayan Sivakumaran.json
Hopefully this is ok!
The webring is in the footer of https://sayansivakumaran.com/.
> Add Sayan Sivakumaran to webring

- data/members/Devon Persing.json
This PR addresses an issue flagged in https://github.com/ericwbailey/a11y-webring.club/issues/124. It fixes a JSON formatting error in one of the member's entries.
> Fix JSON error

- data/members/Rachel Cherry.json
> Add Rachel Cherry as member

- data/members/Trevor Pierce.json
Hi Eric, I'm Trevor. I've been an accessibility specialist and frontend engineer for going on eight years. I just relaunched my personal site and would like to be added to the `a11y-webring`.
Please let me know if I can provide further information and I'll follow up promptly.
> Requesting to add Trevor Pierce.

- data/members/Rachel Cherry.json
Thanks for the update, @ericwbailey!
> Adding Github profile to Rachel Cherry member info

- data/members/Andrew Hedges.json
> Update Andrew Hedges.json

- data/members/Winnie Bosibori.json
> Update Winnie Bosibori.json

- data/members/Saptak S.json
Adds github link and removes twitter link.
> Update Saptak S.json

- data/members/Matt Obee.json
> Update Matt Obee.json

- data/members/Cristian Díaz.json
> Update Cristian Díaz.json

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/addition.yml
- includes/members.njk
This PR addresses https://github.com/ericwbailey/a11y-webring.club/issues/131. It removes Twitter from the webring.
> Remove Twitter

- data/members/Daniela Kubesch.json
I now have an RSS feed, woohoo!
> Update Daniela Kubesch.json

- data/members/Anne Sturdivant.json
Hello! Requesting to join the fantastic a11y-webring.club! A fresh accessibility statement can be found on my weblog here: https://weblog.anniegreens.lol/accessibility-statement
> Create Anne Sturdivant.json

- data/members/Ian Lloyd.json
Added myself. Feels like 1995, man! :D
> Create Ian Lloyd.json

- data/members/Ricky Onsman.json
> Create Ricky Onsman.json

- data/members/Elizabeth McCready_GingerKiwi
Add the Ginger Kiwi blog and to the webring in JSON doc.
> Create Elizabeth McCready_GingerKiwi

- includes/members.njk
- includes/script.njk
- includes/widget.njk
- package.json
- site.css
Some folks want a list, some folks want a grid.
> Add toggle for displaying members in a list or grid

- data/members/Elizabeth McCready.json
Change .blog to .dev and add rss link
add " " around rss feed link
> Update Elizabeth McCready.json

- data/members/Tevin Steinke.json
> Create Tevin Steinke.json

- data/members/Daniel Henderson-Ede.json
Love this idea, thanks for setting this up Eric!
> Add Daniel Henderson-Ede

- data/members/Steve Frenzel.json
> Create Steve Frenzel.json

- data/members/Jan Maarten.json
> Update Jan Maarten.json

- data/members/Muath Khraisat.json
Submitting my site for consideration. Thanks!
> Added Muath Khraisat JSON file

- data/metadata.json
- includes/footer.njk
- includes/head.njk
- includes/intro.njk
- includes/legal.njk
- site.css
This PR adds some slight tweaks to the design post redesign soft launch.
> Design tweaks

- data/members/Eva Decker.json
Would love to join!
Webrings here: https://eva.town/webrings
> Create Eva Decker.json

- data/members/Helen Chong.json
Hi, I would like to join a11y-webring.club. Thank you!
(Pull request recreated since I deleted my fork before the previous PR was merged)
> Add Helen Chong to members list

- data/members/Kazuhiko Tsuchiya.json
I would love to join the a11y-webring.club.
Thank you.
> Create Kazuhiko Tsuchiya.json

- .eleventy.js
- includes/footer.njk
- includes/intro.njk
- includes/widget.njk
- site.css
This PR addresses https://github.com/ericwbailey/a11y-webring.club/issues/185. Additionally it makes a few tweaks to layout and copy.
> Style tweaks and bugfixes

- data/members/E.L. Guerrero.json
I'd like to be a part of the webring! Please let me know if I've done the webring code snippet properly, or if I should amend!
Thank you!
> Create E.L. Guerrero.json

- data/members/Eva Decker.json
> Update Eva Decker.json

- data/members/Coding Otaku.json
I'd love to join the accessibility webring!
I've added the webring links to [my homepage](https://codingotaku.com/#webrings).
> Add Coding Otaku

- data/members/Coding Otaku.json
Sorry, I missed a comma in my previous PR (#199) that's already merged. This should fix it.
> fix missing comma

- data/members/Nic Chan
> Create Nic Chan.json

- data/members/Helen Chong.json
I would like to add a link to my Bluesky account to my member information. Thank you.
> Update member information: Helen Chong's Bluesky account

- data/members/Andreas Nedbal.json
I'd love to join this webring! 👋 
Added the webring links [to my homepage](https://pixelde.su) (a random webring is picked to be at the top of the bottom-most section, the others are all in a `<details>` element below).
Both an accessibility statement and a statement on my (little) JS usage can be found on my [colophon page](https://pixelde.su/colophon).
> Create Andreas Nedbal.json

- data/members/Hedy.json
Hi! I've tried to make my site accessible as far as my understanding goes, let me know if there's any issues.
> Add home.hedy.dev

- data/members/Michael Kitzman.json
Submitting my site for consideration. Thank you.
> Add Michael Kitzman

- data/members/Helen Chong.json
Hi, I would like to update the link to my Mastodon account. Thank you.
> Update Helen Chong's Mastodon account link

- data/members/MarySeph.json
Hello! I would like to be part of the webring!
> Add MarySeph.json

- data/members/Caitlyn Mayers.json
> Adding Caitlyn Mayers to the ring

- data/members/Silvestar Bistrović.json
> Adding Silvestar Bistrović to the ring

- data/members/Sunniva Lovstad.json
Hello! May I join this webring? <span aria-label="Happy ASCII face with eyes closed">^_^</span> (I don’t know what to write here, apologies!)
> Add Sunniva Løvstad to the ring

- data/members/Ariel Salminen.json
- package-lock.json
Hey, first of all, a nice project! I’m hoping to join this webring if possible. Here’s my public-facing [accessibility statement](https://arielsalminen.com/accessibility/) and [webrings page](https://arielsalminen.com/webrings/) that I’ve linked to on the PR.
> Adds arielsalminen.com

- data/members/Zachary Kai.json
May I please join the webring? Thanks very much in advance! I've added the webring links to my homepage: https://zacharykai.net/ and webrings page: https://zacharykai.net/webrings and I have an accessibility statement: https://zacharykai.net/accessibility
> Create Zachary Kai.json

- data/members/Travis Jeans.json
- functions/common/utils.js
Based on my post in issue #226, I tried changing a couple of things in case it helps with debugging.
> Changed includes() to startsWith() and removed index.html from my url

- data/members/Erin White.json
Hi Eric! Thanks for running this web ring. Respectfully requesting to join - thank you!
> Add Erin White

- data/members/Pandu Supriyono.json
Hello!
Hereby my submission to join the webring. My thanks!
> add Pandu Supriyono

- data/members/Karolina Szczur.json
Hey @ericwbailey 👋🏻 
Thank you for creating the a11y webring! I absolutely loved the website and the instructions were super clear, too.
Have a lovely day ☀️
> Create Karolina Szczur.json

- data/members/Boyan Kostov.json
Hello, nice to meet you. It'd be awesome if I could join your webring.
> Add Boyan Kostov

- data/members/Helen Chong.json
Hi, I would like to update my personal information in the webring by adding a link to my Codeberg profile. Thank you!
> Add Helen Chong's Codeberg Link

- data/members/James Coffee Blog.json
This PR adds my website, [James' Coffee Blog](https://jamesg.blog) (https://jamesg.blog), to the a11y Webring.
I build a lot of web tools and spend a lot of time thinking about usability and user preferences.
I have an [accessibility statement on my website](https://jamesg.blog/accessibility), as well as a web reader service I maintain, [Artemis](https://artemis.jamesg.blog/accessibility).
> Add James' Coffee Blog
